require(ggpubr)
require(forcats)
require(ggforce)
require(lubridate)
require(RColorBrewer)
require(viridis)
require(tidyverse)
require(ggplot2)
require(bbmle)
require(dplyr)
require(manipulate)
require(visreg) 
require(ggridges)
require(reshape2)
require(cowplot)
require(ggmap)
require(ggspatial)
require(sf)
require(spData)
require(ggsn)
require(extrafont)
require(knitr)
require(parzer)
require(readxl)

cat("ENS telemetry project")
